version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
      - ./wp-mobile-detector:/var/www/html/wp-content/plugins/wp-mobile-detector/
    networks:
      - wordpress-net
      - db-net
      - attacker-net
  
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - db-net
  
  attacker:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile-Attacker
    container_name: Attacker
    restart: "no"
    privileged: true
    volumes: 
      - attacker-vol:/var/lib/attacker-vol/data
    networks:
      - attacker-net
      - wordpress-net
 
  sonarqube:
    image: sonarqube:latest
    restart: always
    ports:
      - 8060:9000
    volumes:
      - ./wp-mobile-detector:/root

networks:
  wordpress-net:
  attacker-net:
  db-net:

volumes:
  wordpress:
  db:
  sonarqube:
  attacker-vol:
