version: '3.2'

services:

  wordpress:
    image: wordpress
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress-vol:/var/www/html
      - ./wp-mobile-detector:/var/www/html/wp-content/plugins/wp-mobile-detector/
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      wordpress-net:
        ipv4_address: 10.0.2.25  
  
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      wordpress-net:
        ipv4_address: 10.0.2.20
  
  attacker:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile-Attacker
    container_name: Attacker
    restart: "no"
    privileged: true
    ports:
      - 8000:8000
    volumes: 
      - attacker-vol:/var/lib/attacker-vol/data
    networks:
      wordpress-net:
        ipv4_address: 10.0.2.15
 
  sonarqube:
    image: sonarqube:latest
    restart: always
    ports:
      - 8060:9000
    volumes:
      - ./wp-mobile-detector:/root

networks:
  wordpress-net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.10/24

volumes:
  wordpress-vol:
  db-vol:
  sonarqube-vol:
  attacker-vol:
